apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  replicas: 4 #Number of replicas of pods
  selector:
    matchLabels:
      app: my-nginx #This selector matches the one in template
  template:
    metadata:
      labels:
        app: my-nginx

    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources: #constrains what given container allowed to use
          limits:
            memory: "128Mi"
            cpu: "200m"
